# Default values for rook-ceph-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: ceph/ceph:v13.2.4-20190109

dataDirHostPath: /var/lib/rook-ssd

dashboardEnabled: true

monCount: 3

devices:
  - name: "sdb"

cephBlockPools:
  - name: replicapool
    settings:
      failureDomain: host
      replicated:
        size: 3

storageClasses:
  - name: rook-ceph-ssd-block
    pool: replicapool
    default: true
    fstype: ext4
    reclaimPolicy: Retain
