#################################################################################
# The Ceph Cluster CRD example
#################################################################################
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: {{ .Values.image }}
  dataDirHostPath: {{ .Values.dataDirHostPath }}
  dashboard:
    enabled: {{ .Values.dashboardEnabled }}
  mon:
    count: {{ .Values.monCount }}
    allowMultiplePerNode: false
  storage:
    useAllNodes: true
    useAllDevices: false
    devices:
      {{- range .Values.devices }}
      -
{{ toYaml . | indent 8 }}
      {{- end }}
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
