{{- $namespace := .Release.Namespace -}} 
{{- range .Values.cephBlockPools }}
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
spec:
{{ toYaml .settings | indent 2 }}
---
{{- end }}
