{{- $namespace := .Release.Namespace -}}
{{- range .Values.storageClasses -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
{{- if .default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: ceph.rook.io/block
parameters:
  pool: {{ .pool }}
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: {{ $namespace }}
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: {{ .fstype }}
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/ 
reclaimPolicy: {{ .reclaimPolicy }}
---
{{- end }}
